name: Parallel jobs
on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30 && echo "First job"
  second:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30 && echo "Third job"